# Cosine similarity

In [1]:
import numpy as np
from numpy import dot
from numpy.linalg import norm
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
# example 1 - Korean

documents = [
    "나는 학생 입니다",
    "나는 좋은 선생님 입니다",
    "당신은 매우 좋은 선생님 입니다",
]
vector = CountVectorizer()
dtm = vector.fit_transform(documents).toarray()

print (dtm)

doc0 = dtm[0]
doc1 = dtm[1]
doc2 = dtm[2]

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

print('문서 0과 문서1의 유사도 :',cos_sim(doc0, doc1))
print('문서 0과 문서2의 유사도 :',cos_sim(doc0, doc2))
print('문서 1와 문서2의 유사도 :',cos_sim(doc1, doc2))

[[1 0 0 0 1 0 1]
 [1 0 0 1 1 1 0]
 [0 1 1 1 1 1 0]]
문서 0과 문서1의 유사도 : 0.5773502691896258
문서 0과 문서2의 유사도 : 0.2581988897471611
문서 1와 문서2의 유사도 : 0.6708203932499369


In [8]:
# example 2 - Korean

documents = [
    "저는 사과 좋아요",
    "저는 바나나 좋아요",
    "저는 바나나 좋아요 저는 바나나 좋아요",
]
vector = CountVectorizer()
dtm = vector.fit_transform(documents).toarray()
print(dtm)

doc0 = dtm[0]
doc1 = dtm[1]
doc2 = dtm[2]

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

print('문서 0과 문서1의 유사도 :',cos_sim(doc0, doc1))
print('문서 0과 문서2의 유사도 :',cos_sim(doc0, doc2))
print('문서 1와 문서2의 유사도 :',cos_sim(doc1, doc2))

[[0 1 1 1]
 [1 0 1 1]
 [2 0 2 2]]
문서 0과 문서1의 유사도 : 0.6666666666666667
문서 0과 문서2의 유사도 : 0.6666666666666667
문서 1와 문서2의 유사도 : 1.0000000000000002


In [9]:
# Example - English

documents = [
    "Lee likes apples",
    "Lee likes bananas",
    "Lee likes bananas and Lee likes bananas",
]
vector = CountVectorizer()
dtm = vector.fit_transform(documents).toarray()
print(dtm)

doc0 = dtm[0]
doc1 = dtm[1]
doc2 = dtm[2]

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

print('Similarity between Doc_0 and Doc_1 :',cos_sim(doc0, doc1))
print('Similarity between Doc_0 and Doc_2 :',cos_sim(doc0, doc2))
print('Similarity between Doc_1 and Doc_2 :',cos_sim(doc1, doc2))

[[0 1 0 1 1]
 [0 0 1 1 1]
 [1 0 2 2 2]]
Similarity between Doc_0 and Doc_1 : 0.6666666666666667
Similarity between Doc_0 and Doc_2 : 0.6405126152203486
Similarity between Doc_1 and Doc_2 : 0.960768922830523
