In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [37]:
df = pd.read_excel("C:\\Users\\oem\\datasets\\iris-dataset.xlsx", header = 0)

df.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [38]:
data = np.array(df, dtype=np.float32)

x_data = data[:, 0:-1]  

y_data = data[:, [-1]]

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.2)

In [39]:
from sklearn.svm import SVC
from sklearn import metrics

svm = SVC(kernel='linear', C=10, gamma = 1)
svm.fit(x_train, y_train)

y_train_pred = svm.predict(x_train)
y_test_pred = svm.predict(x_test)
 
train_acc = metrics.accuracy_score(y_train_pred, y_train)
test_acc = metrics.accuracy_score(y_test_pred, y_test)

print(f'Train Accuracy: {train_acc:.3f}')
print(f'Test Accuracy: {test_acc:.3f}')

Train Accuracy: 0.975
Test Accuracy: 0.967


C:\Users\oem\.conda\envs\TF_v2\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [40]:
from sklearn.metrics import confusion_matrix, classification_report

actual = np.array(y_test)
pred = np.array(y_test_pred)

con = confusion_matrix(pred, actual)
print (con)


target_names = ['Setosa','Versicolor','virginica']
b = classification_report(pred, actual, target_names = target_names)
print (b)

[[11  0  0]
 [ 0  9  0]
 [ 0  1  9]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       0.90      1.00      0.95         9
   virginica       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

